# Site settings
author: Zachary Quinn
title: My Experience at Flatiron
header-img: img/home-bg.png
email: zacharytq@gmail.com
copyright_name: Zachary Quinn
description: > # this means to ignore newlines until "baseurl:"
  Learning to Code While Working Full Time
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  zacharytq

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
